# Generated by Django 4.1.2 on 2022-10-29 00:20

from django.db import migrations, models
import drug_app.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Drug",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=50,
                        unique=True,
                        validators=[drug_app.validators.NameValidator()],
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        validators=[drug_app.validators.integer_length]
                    ),
                ),
                ("exp_date", models.DateField()),
                ("drug_price", models.DecimalField(decimal_places=2, max_digits=4)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
    ]
