# Generated by Django 4.1.2 on 2022-10-29 00:20

from django.db import migrations, models
import django.db.models.deletion
import drug_app.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("drug_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PE", "Pending"),
                            ("CO", "Completed"),
                            ("RE", "Rejected"),
                            ("CA", "Canceled"),
                        ],
                        default="PE",
                        max_length=2,
                    ),
                ),
                ("description", models.TextField()),
                ("created_at", models.DateField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="OrderedDrug",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        validators=[drug_app.validators.integer_length]
                    ),
                ),
                ("exp_date", models.DateField()),
                ("drug_price", models.DecimalField(decimal_places=2, max_digits=4)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        max_length=50, validators=[drug_app.validators.NameValidator()]
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ordered_drugs",
                        to="orderapp.order",
                    ),
                ),
                (
                    "origindrug",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="origin_drug",
                        to="drug_app.drug",
                    ),
                ),
            ],
        ),
    ]
